[project]
name = "hdl-core"
version = "0.1.0"
description = "HDL core IP library"
readme = "README.md"
authors = [
    { name = "Caspar Trittibach", email = "ctrittibach@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cocotb>=2.0",
    "cocotbext-axi>=0.1.28",
]

[dependency-groups]
dev = [
    "pytest>=8.2.1",
    "ruff>=0.6.9",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["ecc/tb", "debounce/tb", "skid_buffer/tb"]
addopts = "--import-mode=importlib"
